Admin/urls.py
from django.contrib import admin
from django.urls import path, include
import myadmin.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(myadmin.urls))
]

myadmin/urls.py
from django.urls import path, include
from. import views

app_name = 'myadmin'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('edit/<forloop_counter>', views.edit, name='edit'),
    path('del/<forloop_counter>', views.delete, name='del'),
    path('cross/<forloop_counter>', views.cross, name='cross'),
    path('savecloud_from_text/', views.savecloud_from_text,
         name='savecloud_from_text'),
    path('check_saveonecloud', views.check_saveonecloud, name='check_saveonecloud'),
]

myadmin/models.py
from django.db import models

# Create your models here.

myadmin/views.py
from django.shortcuts import render, redirect, render_to_response, HttpResponse
import re
from django.http import JsonResponse
import json
from pymongo import MongoClient
import time

# Create your views here.
to_do_list = [

    {'task': '任务一', 'process': False},
    {'task': '任务二', 'process': True},
]


def mongo_init():
    global mongo_use
    mongo_client = MongoClient('localhost', 27017)
    mongo_db = mongo_client['CLuo_Admin_App']
    mongo_use = mongo_db['myadmin']
    return mongo_use


def home(request):

    to_do = {'to_do_list': to_do_list}
    if request.method == 'POST':
        if request.POST['to_do'].strip() == '':
            to_do['errno'] = '警告！ 您输入的为空值'
            return render(request, 'myadmin/home.html', to_do)
        else:
            to_do['errno'] = '添加成功'
            to_do['to_do_list'].append(
                {'task': request.POST['to_do'], 'process': False})
            print(to_do)
            return render(request, 'myadmin/home.html', to_do)
    elif request.method == 'GET':
        return render(request, 'myadmin/home.html', to_do)


def about(request):
    return render(request, 'myadmin/about.html')


def edit(request, forloop_counter):
    to_do = {'to_do_list': to_do_list}
    if request.method == 'POST':
        if request.POST['edit_task'].strip() == '':
            to_do['errno'] = '警告！ 您输入的为空值'
            return render(request, 'myadmin/edit.html', to_do)
        else:
            to_do['errno'] = '添加成功'
            to_do_list[int(forloop_counter) -
                       1]['task'] = request.POST['edit_task']
            print(to_do)
            return redirect('myadmin:home', to_do)
    else:
        content = {'edit_task': to_do_list[int(forloop_counter) - 1]['task']}
        return render(request, 'myadmin/edit.html', content)


def delete(request, forloop_counter):
    to_do_list.pop(int(forloop_counter) - 1)
    return redirect('myadmin:home')


def cross(requset, forloop_counter):
    print(forloop_counter)
    print(requset.POST['process'])
    if int(requset.POST['process']) == 1:

        to_do_list[int(forloop_counter) - 1]['process'] = False
        return redirect('myadmin:home')
    else:
        to_do_list[int(forloop_counter) - 1]['process'] = True
        return redirect('myadmin:home')


# def sdahkd(cloud_text):
# 	re_compile = re.compile('https://pan.b.*?\\r', re.S)
# 	# 所有账号含密码的字符串
#     cloud_lines = re.findall(re_compile, cloud_text)
# 	print(cloud_lines)
# 	for i in cloud_lines:
# 		i = ''.join(i.split())
#         url = re.search("(https:.*?)/", i).group(1)
#         print(url)
#         pwd = re.search('提取码(.*?)复', i).group(1)
#         print(pwd)
#     return 1


def savecloud_from_text(request):
    """
    保存网盘
    """
    # 提取初始化账户信息
    # 格式为{'account':xxx,'process': None,}
    global savecloud_from_text_data
    mongo_use = mongo_init()
    try:
        account_m = mongo_use.find_one({'_id': 'admin'})['account']
        print(account_m)
    except Exception as e:
        # 数据库账号信息
        account_m = {'_id': 'admin', 'account': ''}
        mongo_use.insert_one(account_m)
        savecloud_from_text()
    if request.method == 'GET':
        data = {'info': account_m}
        return render(request, 'myadmin/savecloud_from_text.html', data)
    else:
        # post请求内的账号信息
        account_p = request.POST.get('account')
        if not account_p == account_m:
            try:
                mongo_use.update_one({'account': account_m}, {
                                 '$set': {'account': account_p}})
                print('账号保存成功')
            except Exception as e:
                print('账号保存失败： %s' % (e))
        cloud_text = request.POST.get('cloud_text')
        info = {
            'account': account_p,
            'process': 'null',
        }
        data = {'info': info}
        while True:
        	print('111111')
        	time.sleep(1)
        return JsonResponse(data, content_type='application/json')
    savecloud_from_text_data = data


def check_saveonecloud(request):
    """
    检测任务监督
    """
    return JsonResponse(savecloud_from_text_data, content_type='application/json')

myadmin/templates/myadmin/about.html
{% extends "myadmin/base.html" %}


{% block title %}关于_CLuo工作室{% endblock title %}
{% block about_active %}active{% endblock about_active %}
{% block css %}myadmin/about.css{% endblock css %}
{% block content%}
      <br>
      <h4>C罗工作室后台工具</h4>
{% endblock content%}

myadmin/templates/myadmin/base.html
{% load static %}
<!doctype html>
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="https://cdn.bootcss.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>-->
<script type='text/javascript' src='{% static "myadmin/js/jquery-3.3.1.min.js" %}'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

 
    <title>{% block title %}{% endblock title %}</title>
 
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

 
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% block css %}{% endblock css %}">
    <link rel="stylesheet" href="{% static 'myadmin/css/base.css' %}">
    
  </head>
 
  <body>
 
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item tag {% block home_active %}{% endblock home_active %}">
            <a class="nav-link" href="{% url 'myadmin:home' %}">CLuo工作室</a>
          </li>
          <li class="nav-item tag {% block about_active %}{% endblock about_active %}">
            <a class="nav-link" href="{% url 'myadmin:about'%}">about</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end" method="POST" action="">
          {% csrf_token %}
          <input name="to_do" class="form-control mr-sm-2" type="text" placeholder="搜索" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
        </form>
      </div>
    </nav>

 
    <main role="main" class="container">
      {% block content %}
      {%endblock content %}
    </main>
 
    
  </body>
</html>

myadmin/templates/myadmin/edit.html
{% extends 'myadmin/base.html'%}
{% load static %}
{% block css%} {% static '/myadmin/css/edit.css'%} {% endblock css%}
{% block title %}添加日程_CLuo工作室{% endblock title	 %}

{% block content %}
 <br>  
{% if errno%}
        {% if errno == '添加成功' %}
          <div class="alert alert-primary alert-dismissible" role="alert">
        {% else%}
          <div class="alert alert-warning alert-dismissible" role="alert">
        {% endif %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><center>{{ errno }}</center></strong> 
      </div>
      {% endif%}
<form id="form-edit" method='POST' action=''>
	{% csrf_token %}
  <div class="form-group">
    <label for="editTodo"></label>
    <input name='edit_task' class="form-control form-control- g" id="editTodo" type="text" value="{{ edit_task }}">
    <small id="help" class="form-text text-muted">在这里编辑待办事项</small>
  </div>
  <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
</form>

{% endblock content %}

myadmin/templates/myadmin/home.html
{% extends "myadmin/base.html" %} {# 引用#}
{% load static %}
{% block css %}{% static 'myadmin/css/home.css' %}{% endblock css %}
{% block title %} 后台首页|CLuo工作室{%  endblock title %}
{% block home_active %}active{% endblock home_active %} {# 高亮#}

{% block content %}
<p>
  <button type="button" class="btn btn-small" id="save_1"><a href="{% url 'myadmin:savecloud_from_text' %}">云盘保存</a></button>
  <button class="btn btn-large" type="button">Large button</button>
</p>
{% endblock content %}

myadmin/templates/myadmin/savecloud_from_text.html
{% extends "myadmin/base.html" %} {# 引用#}
{% load static %}
{% block css %}{% static 'myadmin/css/home.css' %}{% endblock css %}
{% block title %} savecloud from text|CLuo工作室{%  endblock title %}
{% block home_active %}active{% endblock home_active %} {# 高亮#}


{% block content %}
<script type='text/javascript' src='{% static "myadmin/js/jquery-3.3.1.min.js" %}'></script>
<script type='text/javascript'>
  $(function(){
    // 初始化
    var account = $('#account');
    var cloud_text = $('#cloud_text');
    var btn = $('#psbtn');
    account.val('{{ info }}')
    
    function submit_task(){
      // 提交ajax
      var account_v = account.val();
      var cloud_text_v = cloud_text.val();

      // 防跨站設置
      $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}' },  
      })

      //提交ajax
      $.ajax({
        url:"{% url 'myadmin:savecloud_from_text' %}", //提交到那里
        type:"POST", //提交类型
        data:{"account":account_v, "cloud_text":cloud_text_v}, //提交的数据
        datType: "text",
        success:function(data1){
          //返回完成进度\
          process_v = data1.info.process;//不加var 为全局变量
          if(process_v == 11){
            alert('结束')
          }
        }
      })

    }
    
    function check_task(){
      $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
      })
      //提交
      $.ajax({
        url: "{% url 'myadmin:check_saveonecloud' %}",
        type:'GET',
        success: function(data1){
          alert(data1.info.process)
        },
      })
    }

    btn.click(function(){
      submit_task();
      var task1 = setInterval(check_task, 10000)

    })
  });
  

</script>


<form method='POST', id="savecloud_from_text">
{% csrf_token %}

    <div class="form-group">
      <label >保存网盘：</label>
      <input type="text" class="form-control" id="account" placeholder="网盘账号（格式：账号----密码----邮箱账号----密码）">
    </div>
    <div class="form-group">
    <textarea  class="form-control" id="cloud_text" rows="3"placeholder="解析的内容"></textarea></div>
    <div>
    <div class="form-group" >
    <div  class="form-control" id="control" title="控制台">
     
    </div></div>
    <div>
    <button id="psbtn" type="button" class="btn btn-dark">运行</button>
    </div>

</form>
{% endblock content %}